version: 2
jobs:
  build:
    working_directory: ~/android-sdk
    docker:
      - image: sygictravel/android-docker-build
    steps:
      - checkout
      - run:
          name: Replace Versions
          command: echo "SKD versioning"
      - run:
          name: Cleanup
          command: |
            gradle clean
      - run:
          name: Gradle Build
          command: |
            gradle :sdk:install
      - run:
          name: Generate Documentation
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              javadoc -d ../doc -sourcepath sdk/src/main/java/ -subpackages com.sygic.travel
              sed -i 's|\(<\!-- ========= END OF TOP NAVBAR ========= -->\)|\1\n<div class=\"contentContainer\"><p>For quick \"Getting started\" see our <a href=\"https:\/\/github\.com\/sygic-travel\/android-sdk\/\" target=\"\_blank\">Github<\/a>\.<\/p><\/div>|' ../doc/overview-summary.html
            fi
      - run:
          name: Upload Documentation
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              aws s3 sync ../doc s3://docs.sygictravelapi.com/android-sdk/master --delete --acl public-read
            fi
      - store_artifacts:
          path: sdk/build/outputs/aar/sdk-release.aar
          destination: st-android-sdk.aar
