version: 2
jobs:
  build:
    working_directory: ~/android-sdk
    docker:
      - image: circleci/android:api-26-alpha
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-{{ checksum "build.gradle" }}
            - v1-gradle-
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Prepare Cache
          command: |
            rm -f  ~/.gradle/caches/modules-2/modules-2.lock
            rm -fr ~/.gradle/caches/*/plugin-resolution/
      - save_cache:
          key: v1-gradle-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          name: Setting Deploy Metadata
          command: |
            if [[ ! -z $CIRCLE_TAG ]]; then
              export SDK_VERSION=${CIRCLE_TAG:1}
              export BINTRAY_USER=$BINTRAY_USER
              export BINTRAY_APIKEY=$ANDROID_SDK_BINTRAY_API_KEY
            fi
      - run:
          name: Generate Documentation
          command: |
            if [[ $CIRCLE_BRANCH = "master" ]] || [[ ! -z $CIRCLE_TAG ]]; then
              ./gradlew :sdk:dokka
            fi
      - run:
          name: Upload Documentation
          command: |
            if [[ $CIRCLE_BRANCH = "master" ]] || [[ ! -z $CIRCLE_TAG ]]; then
              DOC_PATH="s3://docs.sygictravelapi.com/android-sdk/master"
              if [[ ! -z $CIRCLE_TAG ]]; then
                DOC_PATH="s3://docs.sygictravelapi.com/android-sdk/$CIRCLE_TAG"
              fi
              aws s3 sync ./sdk/build/dokkaDoc $DOC_PATH --delete --acl public-read
            fi
      - run:
          name: Upload SDK to Bintray
          command: |
            if [[ ! -z $CIRCLE_TAG ]]; then
              ./gradlew install bintray
            fi
deployment:
  fake_deploy_for_cci2:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"
